language: node_js
node_js:
  - '10'
  - '8'
  - '6'
cache:
  directories:
    - $HOME/.npm
before_install:
  - npm install --global npm@6.4.1
  - npm --version
after_script: 'cat ./coverage/lcov.info | ./node_modules/.bin/coveralls'
